#include <std.h>
#include "a1.h"

inherit "/std/guilds/spell_room_any";

void create() {
    ::create();
    set("short", "Global%^YELLOW%^ALL%^RESET%^spells");
  set("long", "This is a room that you can train Global%^YELLOW%^ALL%^RESET%^spells for all players. You need to join a guild to train spells for a specific guild to learn attack skills or spells.\n");
    set_property("light", 2);
    set_property("indoors", 1);
    set_property("no attack", 1); 
    set_property("no scry", 1);
    set_property("no teleport", 1);
    set_property("no summon", 1);
    set_property("no cast", 1);
    set_join_room("/d/damned/guilds/join_rooms/child_join");


    add_exit("/d/daybreak/room/N1", "out");
    add_exit("/d/1tlny/skill_rooms/skill_room_all", "east");
    add_exit(PATH+"spell_room_blade", "down");


//NEW
add_spell("flamming grasp", 1);
add_spell("freezing grasp", 1);


add_spell("holy fury", 1);
add_spell("mold nether staff", 1);
add_spell("mold nether robe", 1);
add_spell("elite orb sacrifice", 1);
add_spell("undead creation", 1);
add_spell("nether gate", 1);
add_spell("major undead creation", 1);
add_spell("forbidden undead creation", 1);
add_spell("elite undead creation", 1);
add_spell("minor undead creation", 1);
add_spell("dark weapon", 1);
add_spell("soul crush", 1);
add_spell("power of darkness", 1);
add_spell("lesser shadow field", 1);
add_spell("summon black weapon", 1);
add_spell("owedquar's fury", 1);
add_spell("owedquar's might", 1);
add_spell("black fire", 1);
add_spell("black edge", 1);
add_spell("dark pact", 1);
add_spell("shadow field", 1);
add_spell("cause weakness", 1);
add_spell("summon holy bane", 1);
add_spell("abyss blast", 1);
add_spell("absorption", 1);
add_spell("greater shadow field", 1);
add_spell("abyss blade", 1);
add_spell("storm of ages", 1);
add_spell("owedquar's wrath", 1);
add_spell("shadow bolt", 1);
add_spell("dark assault", 1);
add_spell("black shroud", 1);
add_spell("stun blade", 1);
add_spell("stone blade", 1);
add_spell("soultaker blade", 1);
add_spell("sanctify blade", 1);
add_spell("lesser plasma blade", 1);
add_spell("lesser essential blade", 1);
add_spell("lesser elemental blade", 1);
add_spell("greater plasma blade", 1);
add_spell("greater essential blade", 1);
add_spell("greater elemental blade", 1);
add_spell("banshee blade", 1);
add_spell("essential blade", 1);
add_spell("elemental blade", 1);
add_spell("holy blade", 1);
add_spell("war-hewn weapon", 1);
add_spell("lich form", 1);
add_spell("bless armour", 1);
add_spell("fury of marghuul", 1);
add_spell("divine transformation", 1);

add_spell("major fortification", 1);
add_spell("enchanter mark", 1);
add_spell("enlarge", 1);
add_spell("embalm corpse", 1);
add_spell("elemental transformation", 1);
add_spell("distance poison", 1);

add_spell("deus ex machina", 1);
add_spell("create food", 1);
add_spell("combat healing", 1);
add_spell("clone", 1);
add_spell("claimed weapon", 1);
add_spell("ceremony of purification", 1);
add_spell("call lightning", 1);
add_spell("call divine strength", 1);
add_spell("body of elements", 1);
add_spell("body disruption", 1);
add_spell("area poison", 1);
add_spell("apportation", 1);
add_spell("animal transformation", 1);
add_spell("wrath of god", 1);
add_spell("wor shad", 1);
add_spell("word of recall", 1);
add_spell("winged flight", 1);
add_spell("wind of death", 1);

add_spell("weaken", 1);
add_spell("way of the ranger", 1);
add_spell("warrior's interment", 1);
add_spell("vengeance of k'thach", 1);
add_spell("vampiric blade", 1);
add_spell("vacuum bolt", 1);
add_spell("unholy armour", 1);
add_spell("undead dimension", 1);
add_spell("true weapon", 1);
add_spell("true heal", 1);
add_spell("true armour", 1);
add_spell("transport undead", 1);
add_spell("transport rune", 1);
add_spell("transport beacon", 1);
add_spell("transport", 1);
add_spell("transmutation", 1);

add_spell("teleport", 1);
add_spell("summon woodland familiar", 1);
add_spell("summon rune", 1);
add_spell("summon lesser elemental", 1);
add_spell("summon lesser demon", 1);
add_spell("summon illusionary guardian", 1);
add_spell("summon guardian angel", 1);
add_spell("summon greater familiar", 1);
add_spell("summon greater elemental", 1);
add_spell("summon greater demon", 1);
add_spell("summon familiar", 1);
add_spell("summon ethereal entity", 1);
add_spell("summon elemental dragon", 1);
add_spell("summon elemental", 1);
add_spell("summon elder seraph", 1);
add_spell("summon desert spirit", 1);
add_spell("summon demon lord", 1);
add_spell("summon demon", 1);
add_spell("summon arch angel", 1);
add_spell("summon aerial servant", 1);
add_spell("summon", 1);
add_spell("suggestion", 1);
add_spell("strength of will", 1);
add_spell("strength in numbers", 1);
add_spell("store spell", 1);
add_spell("stabilize familiar", 1);
add_spell("soul gate", 1);
add_spell("smite", 1);
add_spell("slow", 1);
add_spell("silent walk", 1);
add_spell("shocking grasp", 1);
add_spell("shields of war", 1);
add_spell("shield of ithian", 1);
add_spell("shadow form", 1);
add_spell("sense aura", 1);
add_spell("self power", 1);
add_spell("see invisible", 1);
add_spell("scry guard", 1);
add_spell("scry", 1);
add_spell("scribe scroll", 1);
add_spell("scales of justice", 1);
add_spell("satisfy thirst", 1);
add_spell("satisfy hunger", 1);
add_spell("sanctuary", 1);
add_spell("sanctify", 1);
add_spell("rot", 1);
//add_spell("ritual generic", 1);
//add_spell("ritualdud", 1);
add_spell("revitalization", 1);
add_spell("retribution of k'thach", 1);
add_spell("resurrect", 1);
add_spell("remove poison", 1);
add_spell("rejuvination", 1);
add_spell("regeneration", 1);
add_spell("regenerate", 1);
add_spell("ranger animal transformation", 1);
add_spell("rain of spears", 1);
add_spell("protection from chaos", 1);
add_spell("preserve rune", 1);
add_spell("preserve corpse", 1);
add_spell("prepare spell", 1);
add_spell("prepare skill", 1);
add_spell("poison weapon", 1);
add_spell("poison rune", 1);
add_spell("nether sight", 1);
add_spell("mirror image", 1);
add_spell("minor puissance", 1);
add_spell("minor fortification", 1);
add_spell("minor accuracy", 1);
add_spell("meteor storm", 1);
add_spell("mass heal", 1);
add_spell("mass barrier", 1);
add_spell("mana vortex", 1);
add_spell("mana drain", 1);
add_spell("major puissance", 1);
add_spell("major accuracy", 1);
add_spell("magic missile", 1);
add_spell("mad rage", 1);
add_spell("lock enchantment", 1);
add_spell("living weapon", 1);
add_spell("link", 1);
add_spell("light of day", 1);
add_spell("lightning bolt", 1);
add_spell("light", 1);
add_spell("lifesteal blade", 1);
add_spell("lifesteal", 1);
add_spell("levitation", 1);
add_spell("lesser elemental strike", 1);
add_spell("lesser elemental storm", 1);
add_spell("lesser elemental bolt", 1);
add_spell("lesser demon sword", 1);
add_spell("lamp of night", 1);
add_spell("killing cloud", 1);
add_spell("iron will", 1);
add_spell("invisibility", 1);
add_spell("intoxication", 1);
add_spell("internal flame", 1);
add_spell("instill poison", 1);
add_spell("infravision", 1);
add_spell("indomitable spirit", 1);
add_spell("increase metabolism", 1);
add_spell("improve statue", 1);
add_spell("improve golem", 1);
add_spell("improve dragon engine", 1);
add_spell("improved invisibility", 1);
add_spell("implosion", 1);
add_spell("imbue spell", 1);
add_spell("imbue skill", 1);
add_spell("icy weapon", 1);
add_spell("ice dagger", 1);
add_spell("holy word", 1);
add_spell("holy strike", 1);
add_spell("holy mission", 1);
add_spell("holy light", 1);
add_spell("holy lamp", 1);
add_spell("holy condemnation", 1);
add_spell("holy awareness", 1);
add_spell("holy aura", 1);
add_spell("holy armour", 1);
add_spell("hex", 1);
add_spell("healing rune", 1);
add_spell("heal", 1);
add_spell("hawk eyes", 1);
add_spell("haste", 1);
add_spell("harm2", 1);
add_spell("harm", 1);
add_spell("hand of the divine", 1);
add_spell("hand of light", 1);
add_spell("hammer of k'thach", 1);
add_spell("hammer of god", 1);
add_spell("greater elemental strike", 1);
add_spell("greater elemental storm", 1);
add_spell("greater elemental bolt", 1);
add_spell("greater demon sword", 1);
add_spell("gate rune", 1);
add_spell("gate hellion", 1);
add_spell("gaseous form", 1);
add_spell("garguth's pounding fist", 1);
add_spell("garguth's open palm", 1);
add_spell("garguth's grasping hand", 1);
add_spell("freeze skin", 1);
add_spell("fox's agility", 1);
add_spell("force shield", 1);
add_spell("flame blade", 1);
add_spell("fire shield", 1);
add_spell("fire protection", 1);
add_spell("fireball", 1);
add_spell("fashion statue", 1);
add_spell("fashion golem", 1);
add_spell("fashion dragon engine", 1);
add_spell("faerie fire", 1);
add_spell("explosive fireball", 1);
add_spell("exploding rune", 1);
add_spell("essence blade", 1);
add_spell("entangle", 1);
add_spell("energy shield", 1);
add_spell("elemental strike", 1);
add_spell("elemental storm", 1);
add_spell("elemental shield", 1);
add_spell("elemental presence", 1);
add_spell("elemental curse", 1);
add_spell("elemental bolt", 1);
add_spell("elemental barrier", 1);
add_spell("elemental bane", 1);
add_spell("elemental aegis", 1);
add_spell("drizzt strike", 1);
add_spell("dranaxar's anti-magic field", 1);
add_spell("drain life", 1);
add_spell("divine punishment", 1);
add_spell("divine might", 1);
add_spell("divine favor", 1);
add_spell("distance healing", 1);
add_spell("distance harming", 1);
add_spell("disruption bolt", 1);
add_spell("dispel rune", 1);
add_spell("dispel magic", 1);
add_spell("detection", 1);
add_spell("demon sword", 1);
add_spell("demon lord sword2", 1);
add_spell("demon lord sword", 1);
add_spell("demonic rebirth", 1);
add_spell("delay rune", 1);
add_spell("delay", 1);
add_spell("decrease metabolism", 1);
add_spell("decay", 1);
add_spell("dark vision", 1);
add_spell("dark of night", 1);
add_spell("darkness", 1);
add_spell("dagger storm", 1);
add_spell("curse", 1);
add_spell("cure serious wounds", 1);
add_spell("cure light wounds", 1);
add_spell("cure critical wounds", 1);
add_spell("create teleport beacon", 1);
add_spell("create elixir of healing", 1);
add_spell("create alabaster potion", 1);
add_spell("counter spell", 1);
add_spell("cold blast", 1);
add_spell("clairvoyance", 1);
add_spell("claim activate", 1);
add_spell("chilling touch", 1);
add_spell("chaos storm", 1);
add_spell("chaos bane", 1);
add_spell("chaos ball", 1);
add_spell("cause serious wounds", 1);
add_spell("cause light wounds", 1);
add_spell("cause critical wounds", 1);
add_spell("call spirit sword", 1);
add_spell("call holy staff", 1);
add_spell("call hammer of faith", 1);
add_spell("call divine plate", 1);
add_spell("call blade of k'thach", 1);
add_spell("burning hands", 1);
add_spell("bolt of righteousness", 1);
add_spell("blur", 1);
add_spell("blizzard", 1);
add_spell("bless weapon", 1);
add_spell("blessing of knowledge", 1);
add_spell("blessing of agility", 1);
add_spell("bind lesser demon", 1);
add_spell("bind greater demon", 1);
add_spell("bind drizzt", 1);
add_spell("bind demon-lord", 1);
add_spell("bind demon lord", 1);
add_spell("bind demon", 1);
add_spell("battle fury", 1);
add_spell("battle aura", 1);
add_spell("awareness", 1);

add_spell("armour of oblivion", 1);
add_spell("armour of faith", 1);
add_spell("anti-magic field", 1);
add_spell("animate zombie", 1);
add_spell("animate wood", 1);
add_spell("animate vampire", 1);
add_spell("animate skeleton", 1);
add_spell("animate lich", 1);
add_spell("animate ghoul", 1);
add_spell("animate ghast", 1);
add_spell("animate dracolich", 1);
add_spell("animate demilich", 1);
add_spell("animate death knight", 1);
add_spell("alter visage", 1);
add_spell("activate powerstone", 1);
add_spell("elite soul union", 1);
add_spell("soul union", 1);
add_spell("major soul union", 1);
add_spell("minor soul union", 1);
add_spell("dark knight infusion", 1);
add_spell("chaos shadow infusion", 1);
add_spell("blood fiend infusion", 1);
add_spell("ghost infusion", 1);
add_spell("induce nether form", 1);
add_spell("rotted zombie infusion", 1);
add_spell("blood hound infusion", 1);
add_spell("bone man infusion", 1);
add_spell("dark breath", 1);
add_spell("undead restoration", 1);
add_spell("forbidden orb finalization", 1);
add_spell("forbidden soul union", 1);
add_spell("soul duplication", 1);
add_spell("major orb finalization", 1);
add_spell("elite orb finalization", 1);
add_spell("orb finalization", 1);
add_spell("minor orb finalization", 1);
add_spell("minor orb sacrifice", 1);
add_spell("major orb sacrifice", 1);
add_spell("soul transference", 1);
add_spell("soul release", 1);
add_spell("orb stabilization", 1);
add_spell("orb sacrifice", 1);
add_spell("total vanish", 1);
add_spell("time leap", 1);
add_spell("assassination blade", 1);
add_spell("pain", 1);
add_spell("edge of inertia", 1);
add_spell("fade", 1);
add_spell("blackout", 1);
add_spell("teleportation", 1);
add_spell("striking point", 1);
add_spell("mental lock", 1);
add_spell("force blade", 1);
add_spell("stun blast", 1);
add_spell("enemy vision", 1);
add_spell("keen detection", 1);
add_spell("pain blade", 1);
add_spell("mind freeze", 1);
add_spell("eye seal", 1);
add_spell("black vision", 1);
add_spell("energize dragon jewel", 1);
add_spell("minor elemental weapon", 1);
add_spell("major elemental weapon", 1);
add_spell("extreme elemental weapon", 1);
add_spell("elemental weapon", 1);
add_spell("create elemental overlord", 1);
add_spell("create elemental dragon", 1);
add_spell("create elemental demon", 1);
add_spell("create elemental warrior", 1);
add_spell("create elemental fighter", 1);
add_spell("planar wrath", 1);
add_spell("energy sphere", 1);
add_spell("elemental breath", 1);
add_spell("greater mass immersion", 1);
add_spell("extreme mass immersion", 1);
add_spell("mass immersion", 1);
add_spell("lesser mass immersion", 1);
add_spell("bind greater mass", 1);
add_spell("bind extreme mass", 1);
add_spell("bind mass", 1);
add_spell("bind lesser mass", 1);
add_spell("mass diffusion", 1);
add_spell("final elemental magic", 1);
add_spell("elemental onslaught", 1);
add_spell("elemental fatality", 1);
add_spell("elemental disaster", 1);
add_spell("elemental force", 1);
add_spell("ultimate elemental burst", 1);
add_spell("extreme elemental burst", 1);
add_spell("major elemental burst", 1);
add_spell("elemental burst", 1);
add_spell("minor elemental burst", 1);
add_spell("ultimate elemental blast", 1);
add_spell("major elemental blast", 1);
add_spell("minor elemental blast", 1);
add_spell("extreme elemental blast", 1);
add_spell("elemental blast", 1);
add_spell("summon extreme mass", 1);
add_spell("mass enhancement", 1);
add_spell("summon ultimate mass", 1);
add_spell("summon greater mass", 1);
add_spell("summon mass", 1);
add_spell("summon lesser mass", 1);
add_spell("unholy rage", 1);
add_spell("owedquar's eyes", 1);
add_spell("mist cloud", 1);
add_spell("holy ward", 1);
add_spell("curse vision", 1);
add_spell("anger charge", 1);

    return;
}

