#include <std.h>

/* This is one of the three magic gems which serve an integral part of the black keep quest. This gem is used to activate the blue arcane orb located in the far east wing of the first floor, and is destroyed upon its use. The gem itself is located inside one of the three chests in the jail room, located in the keep's basement. To get it, a thief must pick open the correct chest while he is under heavy attack from waves of random mobs generated by the energy mass inside the room. A large party is highly recommended for this task, and it is virtually impossible for a thief to do solo due to his longterm skills being interrupted if he has to fight. */

inherit OBJECT;

void create() {
::create();
set_name("blue gem");
set("id", ({ "gem", "blue gem" }));
set_short("%^BLUE%^A blue gem%^RESET%^");
set_long("This is a very shiny gem, completely blue in color without the slightest trace of color deviation. As it rests in your hand you feel extremely high surges of power throbbing in it.");
set_property("no save", 1);
set_weight(50);
set_value(250000);
}
