#include <std.h>
#include "../keep.h"

/* This is one of the three chests that are located in the black keep jail room. This chest cannot be carried out of the room, and is locked without a key. A thief must pick this chest open while he is under attack by constant droves of monsters generated by the energy mass present in the room. This chest however is a decoy, for it carries nothing. */

inherit "/std/bag_logic";

void create() {
::create();
set_name("chest");
set("id", ({ "chest", "well built chest", "built chest" }));
set_short("A well built chest");
set_long("This is a very well built wooden chest, heavily chained to the ground and locked tightly.");
set_weight(10000000);
set_value(0);
set_max_internal_encumbrance(1500);
set_possible_to_close(1);
toggle_closed();
set_lock("locked");
set_lock_level(25);
}
